name: Deploy DEV

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: DEV

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Build React application
        run: npm run build
        env:
            VITE_APP_ENV: ${{ vars.APP_ENV }}
            VITE_BASE_PATH: ${{ vars.BASE_PATH }}
      
      - name: Deploy to DEV
        uses: peaceiris/actions-gh-pages@v4
        with:
         github_token: ${{ secrets.GITHUB_TOKEN }}
         publish_dir: ./dist
         destination_dir: dev

      - name: Check build paths
        run: cat dist/index.html